export const data = [
    {
        id: 0,
        coords: {
            latitude: -33.46457909220616,
            longitude: -70.6309638441885,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
        },
        name_sucursal: "Tienda Productos El Pueblo",
        description: "Somos una empresa familiar con vasta experiencia y trayectaria en la elaboración de alimentos libres de gluten. Nuestro compromiso es satisfacer la necesidad de consumir alimentos libres de gluten en los que confíen que nunca les causarán problemas de salud y al alcance del bolsillo, mejorando así la calidad de vida de las personas que tengan o quieran llevar una dieta sin gluten. Para Productos El Pueblo lo más importante son las personas. *Visitar página web para encontrar distribuidores de sus productos.",
        direccion: "Av. Portugal 1566, Santiago, Región Metropolitana",
        delivery: "Si, a todo Santiago (incluidas zonas rurales) y Regiones.",
        contact: "+56 2 3307 8010 - +56 2 2401 6896",
        social: "IG: @productos_el_pueblo",
        webpage: "https://productoselpueblo.cl/",
        horario: "9:00 - 17:30, Domingo cerrado.",
    },
    {
        id: 1,
        coords: {
            latitude: -33.46432336180567,
            longitude: -70.59747086459537,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
        },
        name_sucursal: "Excepto Gluten",
        description: "Tienda de alimentos caseros e importados sin gluten, libres de soya, sin leche de vaca, en un 90% además sin huevo, somos celiacos, aplv y aam. Nuestra misión es poder ofrecer productos que puedan entregar a la comunidad celíaca la garantía de comer sin culpas o temores, la garantía de que lo que lleven a su mesa está hecho con cariño y con todo el respeto que merece el saber que lo que preparamos será compartido por una familia que por primera vez probará un barquillo de helado o un bizcocho de torta (nos aburrimos a veces del merengue); en fin, por eso y por muchas oras razones es que nos seguiremos nuestra misión, felices y agradecidas de la excelente recepción de nuestro cariño transformado en Excepto Gluten.",
        direccion: "Av. Grecia 3234, Ñuñoa, Región Metropolitana.",
        delivery: "No se indica.",
        contact: "+56 9 6231 4661 - exceptogluten@gmail.com",
        social: "IG: @_exceptogluten_ - Twitter: @ExceptoGluten",
        webpage: "https://exceptogluten.wordpress.com/",
        horario: "8:30 - 17:00, Domingo cerrado.",
    },
    {
        id: 2,
        coords: {
            latitude: -33.448124301252825,
            longitude: -70.59243989388763,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
        },
        name_sucursal: "Panart Chile",
        description: "Proyecto familiar que surge luego de ver la falta de alternativas de calidad para comer sin gluten y/o con restricciones alimentarias. Panart abrió sus puertas el año 2017 luego de varios meses de arduo trabajo en las distintas preparaciones que hoy en día se ofrecen en el local. Día a día estamos innovando y desarrollando nuevos productos para que así los celiacos, intolerantes al gluten o alérgicos puedan compartir con sus familias, sin que ellos se percaten que es sin gluten, ya que son igual o de mejor calidad que las preparaciones con gluten. Cabe mencionar que hay investigaciones que han demostrado que evitar el gluten es beneficioso para el sistema digestivo, reduce el colesterol y mejora los niveles de energía. ¡Así que anímate y no dudes en venir a visitarnos, te esperamos en nuestra pequeña casa sin gluten!",
        direccion: "Avda. Pdte. Batlle y Ordóñez 3545, Ñuñoa. Región Metropolitana.",
        delivery: "Si, pero solo en Santiago. Disponible en UberEats y Cornershop.",
        contact: "+56 2 22051330 - WhatsApp +56939310115 - contacto@panart.cl",
        social: "IG: @panartchile",
        webpage: "https://www.panart.cl/",
        horario: "Martes a Viernes 11 a 19 hrs. Sábado: 11 a 18 hrs. Domingo y Lunes cerrado",
    },
    {
        id: 3,
        coords: {
            latitude: -33.60948869853133,
            longitude: -70.57285476459538,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
        },
        name_sucursal: "Placer Celíaco. Pastelería libre de Gluten",
        description: "Creemos que ser celiaco no debe ser sinónimo de una vida sin sabor. Somos Loreto y Rodrigo, juntos trabajamos en Placer Celiaco, donde ofrecemos productos de primera calidad para personas celiacas. Sobre todo, productos llenos de sabor y cariño, porque hemos vivido en carne propia las limitaciones de la comida. Te invitamos a probar nuestras recetas originales, como hechas en casa, porque así es como nos gusta alimentarnos en primer lugar: saludablemente y con el sabor del hogar",
        direccion: "Sta. Elena 255, 8150000 Puente Alto, Región Metropolitana",
        delivery: "Si, pero solo para comunas: Puente Alto, La Florida, San Miguel, La Reina, Santiago. No hay detalles sobre regiones o el resto de Santiago.",
        contact: "+56 9 5970 7748 - +56 9 5912 4395",
        social: "IG: @placerceliaco - FB: Placer Celiaco",
        webpage: "https://placerceliaco.cl/",
        horario: "10:00 - 18:00, Domingo cerrado.",
    },
    {
        id: 4,
        coords: {
            latitude: -33.43018962115342,
            longitude: -70.6183601000806,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
        },
        name_sucursal: "QUIMEY SUSHI FUSION & GLUTEN FREE",
        description: "𝖯𝗋𝗂𝗆𝖾𝗋 Sushi Gluten Free de Chile, Pizzas, Burger, Pastelería, SOMOS CELIAC@S, Vegan, Embarazadas, Aplv Aam Keto.",
        direccion: "Dr. Manuel Barros Borgoño 160, Local 104, Providencia, Región Metropolitana",
        delivery: "Si, el costo es calculado por distancia, a casi todo Santiago. Si el despacho esta fuera de las zonas de pedidos online (no se especifica cuales son), se debe contactar directamente con ellos para coordinar.",
        contact: "+56 9 3420 0177, +56 2 3339 9922, +56 2 3223 8936 - pedidosquimeysushi@gmail.com",
        social: "IG: @quimeysushi Twitter: @quimeysushi - FB: Quimey Fusion & Gluten Free",
        webpage: "https://www.quimeysushi.cl/",
        horario: "12:00 a 22:00, Viernes 12:00 a 23:00 Horas, Domingo cerrado.",
    },
    {
        id: 5,
        coords: {
            latitude: -33.49072439805979,
            longitude: -70.5774716527832,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
        },
        name_sucursal: "Thani Bake Shop",
        description: "Somos 100% libre de gluten, el 95% de nuestros productos son sin lactosa, contamos con alternativas veganas, sin leche y sin azúcar añadida. Hace aproximadamente 27 años, me diagnosticaron como celiaca, antes de ello llegue a pesar 41 kilos, una extrema delgadez para mi metro sesenta de estatura, luego de pasar por innumerables médicos y diagnósticos como stress, colón irritable y otros, finalmente me diagnosticaron certeramente, luego de ello mi vida cambió completamente. Debo confesar que amo “pastelear” y que luego del diagnóstico comencé a elaborar pasteles, los que disfrutaban mi familia, especialmente 2 de mis 4 hijos que también son celiacos, Así fue como amigos y conocidos comenzaron a hacerme pedidos de pasteleria sin gluten y sin lactosa, soy ingeniera de profesión y trabaje muchos años en ello, pero el 2018 decidí­ a cumplir un sueño que tenía hace un tiempo, y es que los celiacos puedan disfrutar de manera segura ricas tortas hechas con cariño y cumpliendo altos estándares de calidad porque sé lo mal que uno lo pasa si no cumple la dieta, muchos me dijieron que estaba loca que iba a dejar mi profesión para dedicarme hacer pasteles!! pero uno debe trabajar para cumplir sus sueños. Por ello los invito a que disfruten de mis productos.",
        direccion: "Av. Quilín 5305, Penalolen, Peñalolén, Región Metropolitana, a Pasos de metro Quilin.",
        delivery: "Si, disponible en UberEats y Cornershop",
        contact: "+56 9 7892 7694 - +56 9 6397 1262 - pedidos@thani.cl",
        social: "IG: @thani.alimentos - FB: Thani Alimentos libres de gluten.",
        webpage: "https://www.thani.cl/",
        horario: "Posee dos registros: De lunes a sábado de 11:00 a 19:00 horas, horario continuado. - Lun. a Sáb.11:00 a 20:00 Dom. y Feriados 11:00 a 19:00.",
    },
    {
        id: 6,
        coords: {
            latitude: -33.439759228151104,
            longitude: -70.64830976016034,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
        },
        name_sucursal: "Biomercado",
        description: "Biomercado abre sus puertas en Septiembre de 2017… nacimos frente a una necesidad que vimos insatisfecha en nuestras vidas, ¿dónde encontrar SOLO productos sin gluten y a buenos precios? No existían lugares especializados… hay muchos lugares de comida saludable que tienen “algunos” productos sin gluten, pero la vida actual nos deja poco tiempo libre para recorrer la ciudad , (además nadie quiere que le saquen un ojo de la cara para llevar una dieta que por nuestra salud debemos cumplir con rigor) , bueno es así como Angela y Marcela (dedicadas hace muchos años a la venta de vestuario y accesorios para novias VIA NOVIA ) decidimos en paralelo iniciar esta aventura de Biomercado sin gluten, fué bastante complejo, pero con ilusión, buena voluntad y el apoyo que día a día sentimos de nuestros clientes nos dá ánimos para continuar en esta senda, aquí encuentras más que un almacén dedicado 100 % a todo tipo de productos sin gluten, encuentras una palabra de aliento, información, datos y tips para toda la comunidad celíaca, sensible al gluten o con alergias alimentarias. Porque estamos completamente comprometidas en este proyecto, les invitamos a esta nueva etapa, Biomercado en línea, dónde podrás encontrar los mismos productos que en la tienda física , pero sin restricciones de horario. Estamos muy felices de los pasitos que dá nuestro emprendimiento, porque sabemos que somos un aporte a la comunidad, muchas gracias por permitirnos ser parte de sus vidas.",
        direccion: "Huerfanos 812, local 15 y acceso San Antonio #258, Local 13 habilitado, Santiago, Región Metropolitana",
        delivery: "Si, contactar para consultar detalles o revisar en pagina web, al realizar compra.",
        contact: "+56 2 2993 2249 - +56 9 3410 9254",
        social: "IG: @biomercadochile - FB: Biomercado",
        webpage: "https://www.biomercado.cl/",
        horario: "Posee dos registros: Lunes a Jueves 9:00 - 18:00, Viernes hasta 17:00, Sabado hasta 14:00, Domingo cerrado. - 9:00 a 13:00, Sabado y domingo cerrado.",
    },
    {
        id: 7,
        coords: {
            latitude: -33.43894397977899,
            longitude: -70.61894904111688,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
        },
        name_sucursal: "Dulce Cariño",
        description: "Pasteleria-Panaderia especializada para celiacos. Encontrarás una amplia variedad de productos libres de gluten.",
        direccion: "Alférez Real 1069, Providencia, Región Metropolitana",
        delivery: "Si, contacto para consultar detalles.",
        contact: "+56 9 6281 9823 - noglutceliacos@gmail.com",
        social: "IG: @dulcecarino_noglut - FB: Dulce Cariño / Sin Gluten",
        webpage: "https://www.dulcecarino.com/ - Inactiva",
        horario: "10:00 - 19:00, Sabado y Domingo cerrado.",
    },
    {
        id: 8,
        coords: {
            latitude: -33.46254586931109,
            longitude: -70.57865971101624,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
        },
        name_sucursal: "Sabores para Alegrar",
        description: "Tienda especializada, sin atencion presencial (Funcionamos a pedido). Sabores deliciosos 100% libres de gluten.",
        direccion: "Totoral 4980, I, 7750000 Ñuñoa, Región Metropolitana",
        delivery: "Si dentro de Santiago, gratis en compras sobre 80.000 . Tambien disponible en PedidosYa. Revisar detalles de pedidos y entrega en FAQ de pagina web.",
        contact: "WhatsApp +569 7777 9897 - Saboresparaalegar@gmail.com",
        social: "IG: @saboresparaalegrar - Twitter: @sabores_alegrar - FB: Sabores para alegrar",
        webpage: "https://www.saboresparaalegrar.cl/ - https://delivery.saboresparaalegrar.cl/",
        horario: "Martes a viernes 14:00 a 18:30, Sábado 13:00 a 16:30, Domingo y Lunes: NO HAY ENTREGAS. Revisar detalles de despacho y retiro en pagina web, horario de atencion o FAQ, hay varios registros desparramados.",
    },
    {
        id: 9,
        coords: {
            latitude: -33.436573,
            longitude: -70.642501,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
        },
        name_sucursal: "De Pícara a Cocinera Gluten Free",
        description: "Poseen registro en Santiago: Monjitas (375) y La Florida (Sin direccion), pero tienda es de Talcahuano. - Delivery de deliciosa repostería libre de gluten a tu gusto!. En De Pícara a Cocinera Gluten Free ofrecemos servicios de calidad que ayudan en gran medida a garantizar que se cumplan sus requisitos. Contamos con profesionales capacitados y que tienen los conocimientos técnicos necesarios sobre el tema. Nuestro servicio al cliente se centra en encontrar soluciones a sus problemas, y nuestras reseñas demuestran que puede confiar en nosotros. No dude en ponerse en contacto en cualquier momento para discutir más a fondo.",
        direccion: "Talcahuano, Brisas del Sol. - Monjitas 375, Of. 17 - Santiago",
        delivery: "Si, revisar en https://picaracocinera.cl/ al realizar el pago, o contactar.",
        contact: "+56 9 6393 4834 - zsandovalw@gmail.com ",
        social: "IG: @depicaraacocinera_glutenfree - FB: De Pícara a Cocinera Gluten Free",
        webpage: "Pagina web en estado Beta: https://de-picara-a-cocinera-gluten-free.ueniweb.com/ - https://picaracocinera.cl/",
        horario: "No hay registro.",
    },
    {
        id: 10,
        coords: {
            latitude: -33.515323251484354,
            longitude: -70.75761875953044,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
        },
        name_sucursal: "El Granero del Mundo",
        description: "Productos para toda alimentación, Semillas, frutos secos, veganos, sin gluten, sin azúcar. Productos de alta calidad, El mejor servicio de atención al cliente, Garantía de devolución en 30 días.",
        direccion: "Av. Los Pajaritos 1306, Maipú, Región Metropolitana",
        delivery: "Si, a todo Santiago.",
        contact: "+56 2 2716 5538 - ventas@elgranerodelmundo.com",
        social: "IG: @elgranerodelmundo - FB: El Granero del Mundo",
        webpage: "https://elgranerodelmundo.com/tienda/",
        horario: "9:00 - 18:30, Sabado 10:00 - 15:00 y Domingo cerrado.",
    },
]